### ISSUE TITLE
[PE-D][Tester E] There is pre-existing data when launching the application for the first time

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F11-3/tp#224]
There is sample/pre-existing data in the application when it is first launched.

I think it could make sense to ensure that the application starts with an empty database when the user first launches it so that the user can focus on adding their own data (patients).

This is a screenshot of the application UI upon launching the app for the first time:

![first-launch-has-data.png](https://raw.githubusercontent.com/zackjh/ped/main/files/708ad495-799b-4dda-ad68-d267b945e36a.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: zackjh/ped#2

**Comment by Jaynon** [comment]
The data is for the user's reference for their first time using and trying out this app and can be deleted
