### ISSUE TITLE
[PE-D][Tester A] When adding patients details with the appointment date, old appointment dates are allowed

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F11-3/tp#245]
Believing that the intention is to allow users to add patients with the new appointment date, would it be considered a flaw if users are allowed to add appointment dates that are already considered the past? E.g. today is 8 Nov, should users be able to edit or add appointment dates that is one month ago like 31 Oct 2024 / in the year 1980s?

(to give a better screenshot)

![image.png](https://raw.githubusercontent.com/cth06-Github/ped/main/files/e1742d03-2afc-4614-9141-a6ee37688185.png)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: cth06-Github/ped#4

**Comment by colinac** [comment]
Appointments may be scheduled in the past for the receptionist's reference
