### ISSUE TITLE
[PE-D][Tester C] Error message for delete command with index 0

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F11-3/tp#247]
![image.png](https://raw.githubusercontent.com/jason-chuah/ped/main/files/bb88015f-38d8-4c12-b14b-543da5f4d7c7.png)
The invalid index error might be more appropriate, similar to the update command.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: jason-chuah/ped#7

**Comment by Jaynon** [comment]
duplicate of #235
