### ISSUE TITLE
[PE-D][Tester A] Better Home address validation

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F11-3/tp#257]
I understand from the user guide that the home address accepts any characters but would it be better if there is a character number limit for home address? Assuming the app is for Singapore-based clinics, addresses shouldn't be that long.

![image.png](https://raw.githubusercontent.com/cth06-Github/ped/main/files/079d83e6-e5ba-48dc-a70f-53877c08c7bb.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: cth06-Github/ped#8

**Comment by Jaynon** [comment]
There is no hard limit to addresses in Singapore. If we set a hard limit, there might be an address in the future that might be longer than it.
