### ISSUE TITLE
[PE-D][Tester D] Name cannot be updated despite it only containing alphanumeric

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F11-3/tp#287]
![Screenshot 2024-11-08 at 7.50.55 PM.png](https://raw.githubusercontent.com/yuanchengg/ped/main/files/39cc11f5-1ff5-43a5-b7f7-fa895046870a.png)

Inputting a long name does not allow the person to be updated despite the name only containing alphanumeric characters and spaces.

Steps to reproduce: 
-	Input ‘update 1 n/Prabhakarna Sriparawardana Attapattu Jayasuriya Laxmana Sivaramakrishna Shivavenkata﻿ Rajashekhara Srinivasna Trichipalli Yekyaparampil Perambdur Chinnaswami Muttuswami Venugopal Iyer’

Expected: Able to update patient details (name)
Actual: Error message that "Names should only contain alphanumeric characters and spaces, and it should not be blank" although name only contains alphanumeric charactes and spaces.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: yuanchengg/ped#12

**Comment by Jaynon** [comment]
![image](https://github.com/user-attachments/assets/bbd583f6-0715-4c6b-a058-695282a66f89)

There is a hidden unicode in your string which is detected by the regex. Once removed, the patient's details can be updated
```
update 1 n/Prabhakarna Sriparawardana Attapattu Jayasuriya Laxmana Sivaramakrishna Shivavenkata Rajashekhara Srinivasna Trichipalli Yekyaparampil Perambdur Chinnaswami Muttuswami Venugopal Iyer
```
